jobs:
  - name: orchestration-service-pr
    plan:
      - get: orchestration-service-pr
        trigger: true
        version: every
      - put: orchestration-service-pr
        params:
          context: $BUILD_JOB_NAME
          path: orchestration-service-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          DEPLOY_PATH: app
        input_mapping:
          orchestration-service: orchestration-service-pr
      - task: terraform-plan-app
        .: (( inject meta.plan.terraform-common-config ))
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((dataworks.terraform_repository))
              tag: ((dataworks.terraform_14_version))
          params:
            TF_INPUT: false
            TF_WORKSPACE: qa
            TF_CLI_ARGS_apply: -lock-timeout=300s
            TF_CLI_ARGS_plan: -lock-timeout=300s
          run:
            path: sh
            dir: orchestration-service/terraform/deploy/app
            args:
              - -exc
              - |
                cp ../../../../terraform-config/terraform.tf .
                cp ../../../../terraform-config/terraform.tfvars .
                terraform init
                terraform plan -var assume_role=ci
          inputs:
            - name: orchestration-service
            - name: terraform-config
        input_mapping:
          orchestration-service: orchestration-service-pr
        on_failure:
          put: orchestration-service-pr
          params:
            context: $BUILD_JOB_NAME
            path: orchestration-service-pr
            status: failure
        on_success:
          put: orchestration-service-pr
          params:
            context: $BUILD_JOB_NAME
            path: orchestration-service-pr
            status: success
