jobs:
- name: qa
  serial_groups: [qa-applies]
  plan:
  - get: dw-al2-ecs-ami
    trigger: true
  - get: orchestration-service
    trigger: true
  - .: (( inject meta.plan.terraform-bootstrap ))
    config:
      params:
        DEPLOY_PATH: app
      inputs:
          - name: dw-al2-ecs-ami
  - .: (( inject meta.plan.terraform-apply ))
    config:
      run:
        dir: 'orchestration-service/terraform/deploy/app'
    params:
      TF_WORKSPACE: qa
  - .: (( inject meta.plan.terraform-plan ))
    config:
      run:
        dir: 'orchestration-service/terraform/deploy/app'
    params:
      TF_WORKSPACE: qa
